name: Build and run examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    container: gcc:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install CMake
        run: apt update && apt install -y cmake
      - name: Run CMake
        run: |
          cmake -B builddir
      - name: Build
        run: |
          g++ -Wall -Wextra -I./include -o example1 src/eng_format.cpp examples/example1.cpp
          g++ -Wall -Wextra -I./include -o demo_eng_format src/eng_format.cpp examples/demo_eng_format.cpp
          g++ -Wall -Wextra -I./include -o demo_factors src/eng_format.cpp examples/demo_factors.cpp
          cd test && make
          cmake --build builddir
      - name: Run examples
        run: |
          ./example1
          ./demo_eng_format
          ./demo_factors
      - name: Run tests
        run: |
          cd test && make check